import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const routesPath = path.join(__dirname, '..', '.svelte-kit', 'cloudflare', '_routes.json');

async function updateRoutesFile() {
    try {
        const routes = {
            version: 1,
            description: "Generated by @sveltejs/adapter-cloudflare",
            include: [
                "/*"
            ],
            exclude: [
                "/_app/*",
                "/571653aa1e234e78a8faffcdb1047449.txt",
                "/BingSiteAuth.xml",
                "/favicon.ico",
                "/favicon.png",
                "/",
                "/__data.json",
                "/blog",
                "/blog/*"
            ]
        };

        await fs.writeFile(routesPath, JSON.stringify(routes, null, 2));
        console.log("Successfully updated _routes.json with specific include/exclude rules.");
    } catch (err) {
        console.error("Failed to write _routes.json:", err);
    }
}

updateRoutesFile();
